apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: plfwk2ohr-nodejs
  janus-idp.io/tekton: plfwk2ohr-nodejs
  backstage.io/kubernetes-id: plfwk2ohr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: plfwk2ohr-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
